services:
  api:
    build:
      context: ./api
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindtech
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
